version: '3'
services:
  postgres:
    ports:
    - "5432:5432"
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    image: postgres
volumes:
  pgdata:
    external: true